##### REDIS ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-forum-api
  labels:
    app: redis-forum-api
spec:
  template:
    metadata:
      name: redis-forum-api
      labels:
        app: redis-forum-api
    spec:
      containers:
        - name: redis-forum-api
          image: redis
          ports:
            - containerPort: 6379
          resources: 
            requests:
              cpu: "10m"
              memory: "64M"
            limits:
              cpu: "100m"
              memory: "256M"
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: redis-forum-api
---
apiVersion: v1
kind: Service
metadata:
  name: redis-forum-api-svc
  labels:
    app: redis-forum-api
    service: redis-forum-api-svc
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-forum-api

##### MYSQL #####
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-forum-api
  labels:
    app: mysql-forum-api
spec:
  template:
    metadata:
      name: mysql-forum-api
      labels:
        app: mysql-forum-api
    spec:
      containers:
        - name: mysql-forum-api
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: "MYSQL_DATABASE"
              value: "forum"
            - name: "MYSQL_USER"
              value: "forum"
            - name: "MYSQL_PASSWORD"
              value: "Bk55yc1u0eiqga6e"
            - name: "MYSQL_RANDOM_ROOT_PASSWORD"
              value: "yes"
            - name: "MYSQL_ROOT_HOST"
              value: "%"
          resources: 
            requests:
              cpu: "10m"
              memory: "64M"
            limits:
              cpu: "100m"
              memory: "256M"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/database.sql
              name: mysqldb
              subPath: database.sql
      volumes:
        - name: mysqldb
          configMap:
            name: mysqldb
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mysql-forum-api
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-forum-api-svc
  labels:
    app: mysql-forum-api
    service: mysql-forum-api-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-forum-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  database.sql: |
    CREATE TABLE `forum`.`usuario`(`id` int(11) NOT NULL AUTO_INCREMENT,
      `nome` TEXT NOT NULL,
      `email` VARCHAR(255) NOT NULL,
      `senha` VARCHAR(255) NOT NULL,
      PRIMARY KEY (`id`));
    CREATE TABLE `forum`.`perfil`(`id` int(11) NOT NULL AUTO_INCREMENT,
      `nome` TEXT NOT NULL,
      PRIMARY KEY (`id`));
    CREATE TABLE `forum`.`usuario_perfis`(`usuario_id` int(11) NOT NULL,
      `perfis_id` int(11) NOT NULL);
    CREATE TABLE `forum`.`curso`(`id` int(11) NOT NULL AUTO_INCREMENT,
      `nome` text NOT NULL,
            `categoria` text NOT NULL,
      PRIMARY KEY (`id`));
    CREATE TABLE `forum`.`resposta`(`id` int(11) NOT NULL AUTO_INCREMENT,
            `autor_id` int(11) NOT NULL,
      `topico_id` int(11) NOT NULL,
            `mensagem` text NOT NULL,
            `solucao`text NOT NULL,
            `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`));
    CREATE TABLE `forum`.`topico`(`id` int(11) NOT NULL AUTO_INCREMENT,
      `titulo` text NOT NULL,
      `mensagem` text NOT NULL,
      `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      `status` text NOT NULL,
      `autor_id` int(11) NOT NULL,
      `curso_id` int(11) NOT NULL,
            PRIMARY KEY (`id`));
    INSERT INTO usuario(nome, email, senha)VALUES('Aluno', 'aluno@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
    INSERT INTO usuario(nome, email, senha)VALUES('Moderador', 'moderador@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
    INSERT INTO perfil(id, nome)VALUES(1, 'ROLE_ALUNO');
    INSERT INTO perfil(id, nome)VALUES(2, 'ROLE_MODERADOR');
    INSERT INTO usuario_perfis(usuario_id, perfis_id)VALUES(1, 1);
    INSERT INTO usuario_perfis(usuario_id, perfis_id)VALUES(2, 2);
    INSERT INTO curso(nome, categoria)VALUES('Spring Boot', 'Programacao');
    INSERT INTO curso(nome, categoria)VALUES('HTML 5', 'Front-end');
    INSERT INTO topico(titulo, mensagem, data_criacao, status, autor_id, curso_id)VALUES('Duvida 1', 'Erro ao criar projeto', '2019-05-05 18:00:00', 'NAO_RESPONDIDO', 1, 1);
    INSERT INTO topico(titulo, mensagem, data_criacao, status, autor_id, curso_id)VALUES('Duvida 2', 'Projeto nao compila', '2019-05-05 19:00:00', 'NAO_RESPONDIDO', 1, 1);
    INSERT INTO topico(titulo, mensagem, data_criacao, status, autor_id, curso_id)VALUES('Duvida 3', 'Tag HTML', '2019-05-05 20:00:00', 'NAO_RESPONDIDO', 1, 2);
    GRANT ALL PRIVILEGES ON *.* TO 'forum'@'%' IDENTIFIED BY 'Bk55yc1u0eiqga6e';
    FLUSH PRIVILEGES;
   
      
      